Running tests for API 'chinesecharacterweb'...
FFFFFFF
======================================================================
FAIL: test_get_all_characters (__main__.TestChineseCharacterWebAPI.test_get_all_characters)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/trevea/Projects/ToolsForTheJobBenchmark/generation/Language/chinesecharacterweb/api_test.py", line 25, in test_get_all_characters
    self.assertIsInstance(result, list)
AssertionError: {'error': 'Expecting value: line 1 column 1 (char 0)', 'response': '<head><title>Not Acceptable!</title></head><body><h1>Not Acceptable!</h1><p>An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security.</p></body></html>'} is not an instance of <class 'list'>

======================================================================
FAIL: test_get_all_characters_count (__main__.TestChineseCharacterWebAPI.test_get_all_characters_count)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/trevea/Projects/ToolsForTheJobBenchmark/generation/Language/chinesecharacterweb/api_test.py", line 31, in test_get_all_characters_count
    self.assertIn('count', result)
AssertionError: 'count' not found in {'error': 'Expecting value: line 1 column 1 (char 0)', 'response': '<head><title>Not Acceptable!</title></head><body><h1>Not Acceptable!</h1><p>An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security.</p></body></html>'}

======================================================================
FAIL: test_get_characters_by_radical (__main__.TestChineseCharacterWebAPI.test_get_characters_by_radical)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/trevea/Projects/ToolsForTheJobBenchmark/generation/Language/chinesecharacterweb/api_test.py", line 35, in test_get_characters_by_radical
    self.assertIsInstance(result, list)
AssertionError: {'error': 'Expecting value: line 1 column 1 (char 0)', 'response': '<head><title>Not Acceptable!</title></head><body><h1>Not Acceptable!</h1><p>An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security.</p></body></html>'} is not an instance of <class 'list'>

======================================================================
FAIL: test_get_fields (__main__.TestChineseCharacterWebAPI.test_get_fields)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/trevea/Projects/ToolsForTheJobBenchmark/generation/Language/chinesecharacterweb/api_test.py", line 20, in test_get_fields
    self.assertIsInstance(result, list)
AssertionError: {'error': 'Expecting value: line 1 column 1 (char 0)', 'response': '<head><title>Not Acceptable!</title></head><body><h1>Not Acceptable!</h1><p>An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security.</p></body></html>'} is not an instance of <class 'list'>

======================================================================
FAIL: test_get_sounds_mandarin (__main__.TestChineseCharacterWebAPI.test_get_sounds_mandarin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/trevea/Projects/ToolsForTheJobBenchmark/generation/Language/chinesecharacterweb/api_test.py", line 45, in test_get_sounds_mandarin
    self.assertIsInstance(result, list)
AssertionError: {'error': 'Expecting value: line 1 column 1 (char 0)', 'response': '<head><title>Not Acceptable!</title></head><body><h1>Not Acceptable!</h1><p>An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security.</p></body></html>'} is not an instance of <class 'list'>

======================================================================
FAIL: test_get_strokes (__main__.TestChineseCharacterWebAPI.test_get_strokes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/trevea/Projects/ToolsForTheJobBenchmark/generation/Language/chinesecharacterweb/api_test.py", line 40, in test_get_strokes
    self.assertIsInstance(result, list)
AssertionError: {'error': 'Expecting value: line 1 column 1 (char 0)', 'response': '<head><title>Not Acceptable!</title></head><body><h1>Not Acceptable!</h1><p>An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security.</p></body></html>'} is not an instance of <class 'list'>

======================================================================
FAIL: test_get_version (__main__.TestChineseCharacterWebAPI.test_get_version)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/trevea/Projects/ToolsForTheJobBenchmark/generation/Language/chinesecharacterweb/api_test.py", line 16, in test_get_version
    self.assertIn('phpVersion', result)
AssertionError: 'phpVersion' not found in {'error': 'Expecting value: line 1 column 1 (char 0)', 'response': '<head><title>Not Acceptable!</title></head><body><h1>Not Acceptable!</h1><p>An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security.</p></body></html>'}

----------------------------------------------------------------------
Ran 7 tests in 0.809s

FAILED (failures=7)
Tests completed for API 'chinesecharacterweb'

==================================================

Running tests for API 'purgomalum'...
.F.FF.F
======================================================================
FAIL: test_contains_profanity_true (__main__.TestPurgoMalumAPI.test_contains_profanity_true)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/trevea/Projects/ToolsForTheJobBenchmark/generation/Language/purgomalum/api_test.py", line 12, in test_contains_profanity_true
    self.assertEqual(result, "true")
AssertionError: 'false' != 'true'
- false
+ true


======================================================================
FAIL: test_filter_text_json_with_profanity (__main__.TestPurgoMalumAPI.test_filter_text_json_with_profanity)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/trevea/Projects/ToolsForTheJobBenchmark/generation/Language/purgomalum/api_test.py", line 20, in test_filter_text_json_with_profanity
    self.assertNotEqual(result['result'], "this is a damn bad sentence")
AssertionError: 'this is a damn bad sentence' == 'this is a damn bad sentence'

======================================================================
FAIL: test_filter_text_plain_with_profanity (__main__.TestPurgoMalumAPI.test_filter_text_plain_with_profanity)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/trevea/Projects/ToolsForTheJobBenchmark/generation/Language/purgomalum/api_test.py", line 24, in test_filter_text_plain_with_profanity
    self.assertNotEqual(result, "this is a damn bad sentence")
AssertionError: 'this is a damn bad sentence' == 'this is a damn bad sentence'

======================================================================
FAIL: test_filter_text_xml_with_profanity (__main__.TestPurgoMalumAPI.test_filter_text_xml_with_profanity)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/trevea/Projects/ToolsForTheJobBenchmark/generation/Language/purgomalum/api_test.py", line 28, in test_filter_text_xml_with_profanity
    self.assertNotIn("<result>this is a damn bad sentence</result>", result)
AssertionError: '<result>this is a damn bad sentence</result>' unexpectedly found in '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><PurgoMalum xmlns="http://www.purgomalum.com"><result>this is a damn bad sentence</result></PurgoMalum>'

----------------------------------------------------------------------
Ran 7 tests in 1.578s

FAILED (failures=4)
Tests completed for API 'purgomalum'

==================================================

Running tests for API 'datamuse'...
Tests completed for API 'datamuse'

==================================================

python3: can't open file '/home/trevea/Projects/ToolsForTheJobBenchmark/generation/Language/datamuse/api_test.py': [Errno 2] No such file or directory
Running tests for API 'chinesetext'...
............
----------------------------------------------------------------------
Ran 12 tests in 9.305s

OK
Tests completed for API 'chinesetext'

==================================================

Running tests for API 'freedictionary'...
.Tests completed for API 'freedictionary'

==================================================

.
----------------------------------------------------------------------
Ran 2 tests in 0.832s

OK