Running tests for API 'uuidandguidgen'...
...F.F
======================================================================
FAIL: test_generate_v3_uuid (__main__.TestUUIDandGUIDGenAPI.test_generate_v3_uuid)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/trevea/Projects/ToolsForTheJobBenchmark/generation/FakeData/uuidandguidgen/api_test.py", line 21, in test_generate_v3_uuid
    self.assertTrue(isinstance(result, str))
AssertionError: False is not true

======================================================================
FAIL: test_generate_v5_uuid (__main__.TestUUIDandGUIDGenAPI.test_generate_v5_uuid)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/trevea/Projects/ToolsForTheJobBenchmark/generation/FakeData/uuidandguidgen/api_test.py", line 32, in test_generate_v5_uuid
    self.assertTrue(isinstance(result, str))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 6 tests in 1.320s

FAILED (failures=2)
Tests completed for API 'uuidandguidgen'

==================================================

Running tests for API 'randomuser'...
.......Tests completed for API 'randomuser'

==================================================

.
----------------------------------------------------------------------
Ran 8 tests in 3.082s

OK
